config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :tuits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tuits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tuit.rb
class Tuit < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tuits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)    
    end
    
end

app/controllers/tuits_controller.rb
class TuitsController < ApplicationController
  before_action :set_tuit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /tuits or /tuits.json
  def index
    @tuits = Tuit.all.order("created_at DESC")
    @tuit = Tuit.new
  end

  # GET /tuits/1 or /tuits/1.json
  def show
  end

  # GET /tuits/new
  def new
    @tuit = current_user.tuits.build
  end

  # GET /tuits/1/edit
  def edit
  end

  # POST /tuits or /tuits.json
  def create
    @tuit = current_user.tuits.build(tuit_params)

    respond_to do |format|
      if @tuit.save
        format.html { redirect_to root_path, notice: "Tuit was successfully created." }
        format.json { render :show, status: :created, location: @tuit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tuits/1 or /tuits/1.json
  def update
    respond_to do |format|
      if @tuit.update(tuit_params)
        format.html { redirect_to @tuit, notice: "Tuit was successfully updated." }
        format.json { render :show, status: :ok, location: @tuit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tuits/1 or /tuits/1.json
  def destroy
    @tuit.destroy
    respond_to do |format|
      format.html { redirect_to tuits_url, notice: "Tuit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tuit
      @tuit = Tuit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tuit_params
      params.require(:tuit).permit(:tuit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tuits_helper.rb
module TuitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuiter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
      </div>
    <% end %> 
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Tuiter</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
      </div>
    </div>

      <div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					<div class="field is-grouped">
						<p class="control">
							<%= link_to 'New Tuit', root_path, class: "button is-info is-inverted" %>
						</p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/tuits/_feed.html.erb
<div class="column is-half">
   <% if user_signed_in? %>
     
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
            </p>
        </figure>
        <div class="media-content">
        <%= render 'tuits/form' %>
        </div>
    </article>
    <% end %>
<% @tuits.each do | tuit | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <%= gravatar_image_tag(tuit.user.email, size: 64, alt: tuit.user.name) %>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                <strong><%= tuit.user.name %></strong><br />
                <small><%= tuit.user.username %></small><br/>
                <p><%= tuit.tuit %></p>
            </div>
            <nav class="level">
                <div class="level-left is-mobile">
                <%= link_to tuit, class: "level-item" do %>
                    <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to edit_tuit_path(tuit), class: "level-item" do %>
                    <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to tuit, method: :delete, data: { confirm: "Are you sure you want to delete this tuit?" } do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
                </div>
            </nav>
            </div>
         </article>
 </div>
<% end %>
</div>

app/views/tuits/_form.html.erb
<%= simple_form_for(@tuit) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :tuit, label: "Tuite about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tuit here...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/tuits/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">tuits</p>
						<p class="title is-6"><%= current_user.tuits.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tuits/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <a class="panel-block">
            Trend 1
        </a>
        <a class="panel-block">
        
            Trend 2
        </a><a class="panel-block">
            Trend 3
        </a><a class="panel-block">
            Trend 4
        </a><a class="panel-block">
            Trend 5
        </a><a class="panel-block">
            Trend 6
        </a>
    </nav>
</div>

app/views/tuits/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Carla Thais</strong>
                        <small>@carthais</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <strong>Andreza Santos</strong>
                        <small>@dezasan</small>
                    </p>
                </div>
            </div>
        </article>
    </div>
</nav>

app/views/tuits/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tuit</h1>
				<%= render 'form', tuit: @tuit %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tuits_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tuits/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in?%>
        <%= render 'profile' %>
      <% else %>
      <%= render 'trends' %>
      <% end %>
      
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/tuits/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tuit</h1>
					<%= render 'form', tuit: @tuit %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tuits_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tuit:</strong>
  <%= @tuit.tuit %>
</p>

<%= link_to 'Edit', edit_tuit_path(@tuit) %> |
<%= link_to 'Back', tuits_path %>